version: "3.1"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=templo_belen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d templo_belen"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.9
    command: -url=jdbc:postgresql://postgres:5432/templo_belen -user=postgres -password=password -connectRetries=60 -locations=filesystem:/flyway/sql/migrations,filesystem:/flyway/sql/dev migrate
    volumes:
      - ./postgres/db_scripts/migrations:/flyway/sql/migrations
      - ./postgres/db_scripts/dev:/flyway/sql/dev
    depends_on:
      postgres:
        condition: service_healthy

  server:
    build: .
    ports:
      - 8000:80
    environment:
      POSTGRES_DB: templo_belen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      FRONTEND_URL: http://localhost:4200
      SECRET_KEY: changeme
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      flyway:
        condition: service_completed_successfully
    restart: "no"

volumes:
  postgres_data:
