version: "3.8"
services:
  postgres-test:
    image: postgres:16
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway-test:
    image: flyway/flyway:11.9
    command: [
      "-url=jdbc:postgresql://postgres-test:5432/test",
      "-user=postgres",
      "-password=password",
      "-connectRetries=60",
      "-locations=filesystem:/flyway/sql/migrations,filesystem:/flyway/sql/dev",
      "migrate"
    ]
    volumes:
      - ./db_scripts/migrations:/flyway/sql/migrations
      - ./db_scripts/dev:/flyway/sql/dev
    depends_on:
      postgres-test:
        condition: service_healthy
