CREATE TABLE members (
    id SERIAL PRIMARY KEY,

    id_number VARCHAR(50) NOT NULL UNIQUE,
    surnames VARCHAR(100) NOT NULL,
    names VARCHAR(200) NOT NULL,
    birthdate DATE,
    birth_country VARCHAR(100),
    residence_country VARCHAR(100),
    address VARCHAR(200),
    phone_number VARCHAR(20),
    cellphone_number VARCHAR(20),
    email VARCHAR(150),
    military_service VARCHAR(50),
    studies_completed VARCHAR(100),
    degree_obtained VARCHAR(100),
    other_studies VARCHAR(100),
    company VARCHAR(100),
    occupation VARCHAR(100),
    eps VARCHAR(50),
    rh VARCHAR(5),
    gender VARCHAR(20),

	leadership VARCHAR(100),
	"current_role" VARCHAR(100),
    zone_pastor VARCHAR(100),
	is_pastor boolean NOT NULL DEFAULT FALSE,
	is_cell_leader boolean NOT NULL DEFAULT FALSE,

	status varchar(1) NOT NULL DEFAULT 'A', -- A=Active, I=Inactive

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50) NOT NULL DEFAULT 'SYS',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(50) NOT NULL DEFAULT 'SYS'
);

INSERT INTO members (
    id_number,
    surnames,
    names,
    birthdate,
    birth_country,
    residence_country,
    address,
    phone_number,
    cellphone_number,
    email,
    military_service,
    studies_completed,
    degree_obtained,
    other_studies,
    company,
    occupation,
    eps,
    rh,
    gender,
    leadership,
    zone_pastor,
    "current_role",
    is_pastor,
    is_cell_leader,
    status
) VALUES (
    '1234567890',
    'González Pérez',
    'Juan Carlos',
    '1990-05-10',
    'Colombia',
    'Colombia',
    'Calle 123 #45-67, Bogotá',
    '6012345678',
    '3001234567',
    'juan.gonzalez@example.com',
    'A1234567',
    'Universidad',
    'Ingeniería de Sistemas',
    'Diplomado en liderazgo organizacional',
    'Tech Solutions S.A.',
    'Desarrollador de Software',
    'Sura',
    'O+',
    'Masculino',
    'Liderazgo Juvenil',
          'Jesus María José',
    'Coordinador',
    FALSE,
    FALSE,
    'A'
);

INSERT INTO members (
    id_number,
    surnames,
    names,
    birthdate,
    birth_country,
    residence_country,
    address,
    phone_number,
    cellphone_number,
    email,
    military_service,
    studies_completed,
    degree_obtained,
    other_studies,
    company,
    occupation,
    eps,
    rh,
    gender,
    leadership,
    zone_pastor,
    "current_role",
    is_pastor,
    is_cell_leader,
    status
) VALUES (
    '707998',
    'Hernandez',
    'Erika',
    '1990-05-10',
    'Venezuela',
    'Colombia',
    'Calle 123 #45-67, Medellin',
    '6012345678',
    '3198888888',
    'erikita@example.com',
    null,
    'Universidad',
    'Licenciatura en computacion',
    null,
    'La Empresa',
    'Desarrollador de Software',
    'Sura',
    'B+',
    'Femenino',
    null,
          'Jesus María José',
    'Nada',
    FALSE,
    FALSE,
    'A'
);